Static analysis Improvements and general clean up
laminas/laminas-inputfilter pull request #54
Opened 2022-06-09 21:10 UTC by gsteel

|    Q          |   A
|-------------- | ------
| BC Break      | Hopefully Not
| QA            | yes

### Description

Sorry for the size of this patch - My original intention was to improve type inference for some seemingly simple stuff but things quickly got out of hand.

I'll do a review and point out the stuff I think might be risky.

Hopefully this will provide decent type checking for input filter specification arrays along with some other improvements

2022-06-09 21:37 UTC, gsteel reviewed
I should probably add a psalm-type for InputFilterSpecification that an InputFilterProvider can return, and the Factory can use

2022-06-09 21:37 UTC, gsteel commented on src/BaseInputFilter.php
> +        assert($this->data !== null);
This method is only ever called once data is non-null

2022-06-09 21:37 UTC, gsteel commented on src/CollectionInputFilter.php
> +
The collection is simply not compatible with a lot of the declared types in `InputFilterInterface` - I duplicated these inherited properties so that I could assign the more specific types. OFC I can revert and re-add the errors to the baseline

2022-06-09 21:37 UTC, gsteel commented on src/CollectionInputFilter.php
> +        $data = ArrayUtils::iteratorToArray($data);
Calling `iteratorToArray` here makes `$this->data` the expected type - at this point, in a collection, $data is a list of data arrays or possibly traversable - it shouldn't make any difference as `parent::setData()` also calls `iteratorToArray` - nonetheless, this might be risky

2022-06-09 21:37 UTC, gsteel commented on src/Factory.php
> +                ? $filterChain->setPluginManager($this->defaultFilterChain->getPluginManager())
It's not actually feasible for `$filterChain` to be null here, but it breaks a couple of mocks in tests that _do_ return null for `getFilterChain` - Same thing for validators from Line 500

2022-06-09 21:37 UTC, gsteel commented on src/InputFilterAbstractServiceFactory.php
> +        assert($validatorChain instanceof ValidatorChain);
New instances will have non-null chains but you can't psalm-assert on a constructor :(

2022-06-09 21:37 UTC, gsteel commented on src/InputFilterInterface.php
> +/**
Hopefully these definitions will provide some handy inference

2022-06-09 21:37 UTC, gsteel commented on src/InputFilterProviderInterface.php
>       * @return array
This should return a new psalm-type for `InputFilterSpecification`

2022-06-09 21:37 UTC, gsteel commented on src/UnfilteredDataInterface.php
> +     * @param array<array-key, mixed> $data
Should probably be changed to `iterable<array-key, mixed>`

2022-06-09 21:47 UTC, gsteel commented
Current psalm failures will be solved by https://github.com/laminas/laminas-validator/pull/128

2022-06-09 21:57 UTC, Ocramius requested changes

2022-06-09 21:57 UTC, Ocramius commented on src/BaseInputFilter.php
> +        /** @psalm-var string $name */
This looks forced: I suggest leaving it be, and expanding the baseline

2022-06-09 21:57 UTC, Ocramius commented on src/BaseInputFilter.php
> +        /** @psalm-var list<string> $inputs */
IMO we shouldn't force this here: larger baseline is better in this case

2022-06-09 21:57 UTC, Ocramius commented on src/BaseInputFilter.php
> +            /** @psalm-var mixed $value */
We can skip this variable assignment - we already suppress the `MixedAssignment` below

2022-06-09 21:57 UTC, Ocramius commented on src/BaseInputFilter.php
> +                /** @psalm-var iterable<array-key, mixed> $value */
This shouldn't be needed: something wrong with inference.

2022-06-09 21:57 UTC, Ocramius commented on src/BaseInputFilter.php
>                  if (! is_array($value) && ! $value instanceof Traversable) {
Perhaps applying De Morgan's here could improve inference?

2022-06-09 21:57 UTC, Ocramius commented on src/CollectionInputFilter.php
> +    protected $validInputs;
These added properties are suspicious, especially if `protected` :|

2022-06-09 21:57 UTC, Ocramius commented on src/CollectionInputFilter.php
> +     * @psalm-assert BaseInputFilter $this->inputFilter
This looks like `@psalm-out` rather than `@psalm-assert` - we don't use this method like an assertion.

2022-06-09 21:57 UTC, Ocramius commented on src/CollectionInputFilter.php
> +     * @psalm-assert array<array-key, mixed> $this->data
This would be picked up as redundant assertion, if used in a context where the given `$data` is already of the right shape 🤔

2022-06-09 21:57 UTC, Ocramius commented on src/CollectionInputFilter.php
> +        /** @psalm-var mixed $item */
Probably better to suppress the mixed assignment, than to add an `@var` block (which prevents inference)

2022-06-09 21:57 UTC, Ocramius commented on src/Factory.php
> +     * @psalm-assert FilterChain $this->defaultFilterChain
All over the patch, I'd say that  `@psalm-assert` is misused: let's not use it as a hack for internal state mutation.

2022-06-09 21:57 UTC, Ocramius commented on src/Factory.php
> +                    /** @psalm-var iterable<array-key, FilterSpecification> $value */
Let's not force the value here - all over the patch, `@var` blocks need to be strongly reduced, preferring inference over declaration

2022-06-09 22:24 UTC, gsteel commented on src/BaseInputFilter.php
>                  if (! is_array($value) && ! $value instanceof Traversable) {
Had to Google De Morgan - still none the wiser!

2022-06-09 22:26 UTC, gsteel commented on src/CollectionInputFilter.php
> +     * @psalm-assert BaseInputFilter $this->inputFilter
I thought `@param-out` only worked for by ref arguments?

2022-06-09 22:43 UTC, gsteel commented on src/BaseInputFilter.php
> +                /** @psalm-var iterable<array-key, mixed> $value */
It's not wrong - just slighty 'off': `psalm: MixedArgumentTypeCoercion: Argument 1 of Laminas\InputFilter\InputFilterInterface::setData expects iterable<array-key, mixed>|null, parent type Traversable|array<array-key, mixed> provided`

I've baselined that

2022-06-09 22:47 UTC, gsteel commented on src/CollectionInputFilter.php
> +     * @psalm-assert BaseInputFilter $this->inputFilter
Most of these asserts could be replaced with null checks where they're missing, and they're missing a fair bit - I favoured the annotation so I didn't have to change the code where it made sense. Would you like me to remove them and re-add to the baseline?

2022-06-10 09:37 UTC, Ocramius requested changes

2022-06-10 09:37 UTC, Ocramius commented on src/CollectionInputFilter.php
> +     * @psalm-assert BaseInputFilter $this->inputFilter
I would say that `@psalm-assert` is the wrong tool for the job here: adding `assert()` where necessary is a better solution.

Alternatively, keep them in baseline for now, but let's get rid of all `@psalm-assert` that are not strictly about asserting inputs

2022-06-10 09:37 UTC, Ocramius commented on src/CollectionInputFilter.php
> +     * @psalm-assert array<array-key, mixed> $this->data
Same as all `@psalm-assert` introduced in this patch: let's remove them and replace them either with manual assertions, or with a larger baseline for now

2022-06-10 09:37 UTC, Ocramius commented on src/CollectionInputFilter.php
> +        $data = ArrayUtils::iteratorToArray($data);
Iterating twice on a potentially closed iterator is IMO worse - can we avoid adding this?

2022-06-10 09:37 UTC, Ocramius commented on src/Input.php
> +        /** @psalm-suppress DeprecatedProperty */
Let's keep these in baseline - they are supposed to be reduced/elided over time

2022-06-10 09:37 UTC, Ocramius commented on src/Input.php
> +        /** @psalm-suppress DeprecatedProperty */
Let's keep these in baseline - they are supposed to be reduced/elided over time

2022-06-10 09:37 UTC, Ocramius commented on src/InputFilterAbstractServiceFactory.php
> +        assert($validatorChain instanceof ValidatorChain);
Even then, asserting shouldn't happen with `psalm-assert` as per discussions above :D

2022-06-10 09:37 UTC, Ocramius commented on src/InputFilterInterface.php
> +<?php // phpcs:disable SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse
Can we perhaps have it on specific lines? :thinking:

2022-06-10 09:37 UTC, Ocramius commented on src/InputFilterPluginManager.php
> +<?php //phpcs:disable WebimpressCodingStandard.PHP.CorrectClassNameCase.Invalid
Let's disable this at `phpcs.xml` level perhaps?

2022-06-10 09:37 UTC, Ocramius commented on src/InputFilterPluginManagerFactory.php
> +<?php //phpcs:disable WebimpressCodingStandard.PHP.CorrectClassNameCase.Invalid
Let's exclude this at phpcs level, perhaps?

2022-06-10 09:37 UTC, Ocramius commented on src/InputInterface.php
> +     * @return array<array-key, string>
BTW, `array<string>` is the same as `array<array-key, string>`

2022-06-10 09:37 UTC, Ocramius commented on src/OptionalInputFilter.php
> +     * @psalm-assert array<array-key, mixed> $this->data
To be dropped

2022-06-10 09:37 UTC, Ocramius commented on src/OptionalInputFilter.php
> -     * @param  iterable|mixed $data
Previously, this allowed `mixed` - now it only allows `iterable|null` :thinking:

2022-06-10 09:37 UTC, Ocramius commented on test/FactoryTest.php
>              ->disableOriginalConstructor()
This can be dropped, replaced by `$this->createMock(InputFilterPluginManager::class)`, without any `@var` declaration

2022-06-10 10:14 UTC, gsteel commented on src/InputFilterPluginManagerFactory.php
> +<?php //phpcs:disable WebimpressCodingStandard.PHP.CorrectClassNameCase.Invalid
I went for the inline suppression because the sniff is wrong - it's complaining that `Interop\Container\ContainerInterface` should actually be `interop\container\containerinterface` - this is probably something to do with Service Manager and that weird psr extension - I could replace with a doc block citing removal when Interop is finally dead? Otherwise, we would potentially be suppressing valid errors elsewhere no?

2022-06-10 10:21 UTC, gsteel commented on src/CollectionInputFilter.php
> +        $data = ArrayUtils::iteratorToArray($data);
parent::setData isn't called here therefore, if the collection is part of a containing input filter, the data is already an array, so iteratorToArray will be receiving an array anyhow - theoretically, this ensures that an iterable _is_ cast to an array if a collection is used as a top-level inputfilter or extended. I'll remove it anyway and baseline any additional errors

2022-06-10 10:24 UTC, gsteel commented on src/InputFilterInterface.php
> +<?php // phpcs:disable SlevomatCodingStandard.Namespaces.UnusedUses.UnusedUse
Yes - good idea, I'll `//phpcs: ignore` the offending lines

2022-06-10 10:25 UTC, Ocramius commented on src/InputFilterPluginManagerFactory.php
> +<?php //phpcs:disable WebimpressCodingStandard.PHP.CorrectClassNameCase.Invalid
Yeh, I'm aware of why this sniff was suppressed here. Thinking further about it, I think this is fine as-is, since the suppression only applies to factory and container definitions

2022-06-10 10:39 UTC, gsteel commented on src/OptionalInputFilter.php
> -     * @param  iterable|mixed $data
The annotation was just wrong imo - the change matches the interface and base abstract - these all stated out as `array|Traversable` and occasionally null too - I've changed this to `iterable<array-key, mixed>|null` - TBF, this could just be `iterable|null` couldn't it? The collection is still mixed, but even then `iterable|null` would be a more precise type - there's a suppression on collection for `ImplementedParamTypeMismatch` that should also be removed most likely.

2022-06-10 10:40 UTC, Ocramius commented on src/OptionalInputFilter.php
> -     * @param  iterable|mixed $data
> The annotation was just wrong imo

Works for me. 

 > TBF, this could just be `iterable|null` couldn't it?

yep

2022-06-10 10:55 UTC, gsteel commented on src/CollectionInputFilter.php
> +
@Ocramius - What shall I do about these added properties? Shall I bin them and re-add to the baseline?

2022-06-10 11:37 UTC, Ocramius commented on src/CollectionInputFilter.php
> +
Yes please: adding more `protected` properties is just more damage, IMO :|

2022-06-10 12:13 UTC, gsteel commented
I think that's all the points attended to @Ocramius - Thank you for the review and all your help :)

2022-06-10 12:37 UTC, Ocramius approved these changes
Awesome, thanks @gsteel!

2022-06-10 12:37 UTC, Ocramius commented on src/CollectionInputFilter.php
> +            return $this->data !== null ? count($this->data) : 0;
Not important, but could've been `count($this->data ?? [])` :D

2022-06-10 12:38 UTC, merged