Adds cookbook recipe for using input filters in forms
laminas/laminas-inputfilter pull request #80
Opened 2022-11-04 12:42 UTC by froschdesign

2022-12-13 21:40 UTC, weierophinney requested changes
Minor changes, but looks good!

2022-12-13 21:40 UTC, weierophinney commented on docs/book/cookbook/input-filter-in-forms.md
> +The following examples shows _two_ potential use cases of laminas-inputfilter within forms of [laminas-form](https://docs.laminas.dev/laminas-form/).
```suggestion
The following examples shows _two_ potential use cases of laminas-inputfilter within [laminas-form](https://docs.laminas.dev/laminas-form/).
```

2022-12-13 21:40 UTC, weierophinney commented on docs/book/cookbook/input-filter-in-forms.md
> +This interface provides one method (`getInputFilterSpecification()`) that is used by a form of laminas-form to create an input filter.
```suggestion
This interface provides one method (`getInputFilterSpecification()`) that is used by a form to create an input filter.
```

Removing a redundancy; it's implied by this point due to the introduction.

2022-12-13 21:40 UTC, weierophinney commented on docs/book/cookbook/input-filter-in-forms.md
> +[Create an input filter as separate class](../intro.md), e.g. `module/Album/src/InputFilter/AlbumInputFilter.php`:
```suggestion
[Create an input filter as a separate class](../intro.md), e.g. `module/Album/src/InputFilter/AlbumInputFilter.php`:
```

2022-12-13 21:40 UTC, weierophinney commented on docs/book/cookbook/input-filter-in-forms.md
> +[Create a form as separate class](https://docs.laminas.dev/laminas-form/v3/quick-start/#factory-backed-form-extension) using the [`init` method](https://docs.laminas.dev/laminas-form/v3/advanced/#ini
```suggestion
[Create a form as a separate class](https://docs.laminas.dev/laminas-form/v3/quick-start/#factory-backed-form-extension), define the [`init` method](https://docs.laminas.dev/laminas-form/v3/advanced/#initialization), implement the interface `Laminas\InputFilter\InputFilterProviderInterface`, and define its inputs via a configuration array; as an example, consider the following definition in a file found at `module/Album/src/Form/AlbumForm.php`:
```

2022-12-13 21:40 UTC, weierophinney commented on docs/book/cookbook/input-filter-in-forms.md
> +Create a form as separate class using the `init` method and set the input filter via the `setInputFilterByName()` method of `Laminas\Form\Form`, e.g. `module/Album/src/Form/AlbumForm.php`:
```suggestion
Create a form as a separate class, define its `init` method, and set the input filter via the `setInputFilterByName()` method of `Laminas\Form\Form`, e.g. `module/Album/src/Form/AlbumForm.php`:
```

2023-04-04 20:55 UTC, froschdesign commented
@weierophinney 
A final review is needed.
Thanks in advance! 👍🏻

2023-04-04 21:24 UTC, weierophinney reviewed
One minor language change, but otherwise good go go!

2023-04-04 21:24 UTC, weierophinney commented on docs/book/cookbook/input-filter-in-forms.md
> +The following examples shows _two_ potential use cases of laminas-inputfilter within [laminas-form](https://docs.laminas.dev/laminas-form/).
```suggestion
The following examples show _two_ potential use cases of laminas-inputfilter within [laminas-form](https://docs.laminas.dev/laminas-form/).
```

2023-04-05 08:44 UTC, merged