Improve inference for `InputFilterPluginManager::get()`
laminas/laminas-inputfilter pull request #97
Opened 2024-01-09 14:41 UTC by gsteel

Currently, `InputFilterPluginManager::get(FQCN::class)` yields the union of `InputFilterInterface|InputInterface`.

Ideally, this would be the given FQCN when it implements one of those interfaces.

Also, the `@method get` docblock is problematic as it trumps any user defined stubs and causes other problems that I can't remember!

Because the plugin manager here is guaranteed to return `InputFilterInterface|InputInterface` as opposed to `T|mixed`, this conflicts with `AbstractPluginManager::get()`.

Furthermore, I think psalm might have issues with `class-string<PsalmAliasOfUnion>`.

This patch provides correct inference for consumers when they provide a FQCN or string alias at the expense of 2 or 3 extra baselined issues that I believe are due to using a union type for `InstanceType` on the class level template.

2024-01-09 15:14 UTC, Xerkus commented on src/Factory.php
> +        assert($inputFilter instanceof InputFilterInterface); // As opposed to InputInterface
How do we know it is not an InputInterface here? InputFilterManager allows both

2024-01-09 15:24 UTC, gsteel commented on src/Factory.php
> +        assert($inputFilter instanceof InputFilterInterface); // As opposed to InputInterface
Because the `createInputFilter` method expects a spec (Array of type `InputFilterSpecification`). Here `$type` defaults to `InputFilter::class` and `InputFilterSpecification['type']` is `class-string<InputFilterInterface>`

2024-01-09 15:27 UTC, Xerkus commented on src/Factory.php
> +        assert($inputFilter instanceof InputFilterInterface); // As opposed to InputInterface
I think this ought to be full check for input filter with meaningful exception, not just an assert since the method is user facing and there is no soft guard somewhere else.

2024-01-09 15:41 UTC, Ocramius commented on src/InputFilterPluginManager.php
> +    }
Isn't the entire signature the same as `@param class-string<T> @return T`? 

Overall OK with this, just seems redundant with the parent DIC declarations

2024-01-09 15:41 UTC, Ocramius approved these changes

2024-01-09 16:07 UTC, Xerkus commented on src/InputFilterPluginManager.php
> +    }
I testing this locally. It seems it could be simplified.

2024-01-09 16:17 UTC, Xerkus commented on src/InputFilterPluginManager.php
> +    }
I tried following:

```
    /**
     * @inheritDoc
     * @template T of InputInterface|InputFilterInterface
     * @param class-string<T>|string $name
     * @psalm-return ($name is class-string<T> ? T : T)
     */
    public function get($name, ?array $options = null)
```

Result is close:
```
ERROR: Trace - test/StaticAnalysis/InputFilterPluginManagerType.php:27:9 - $input: Laminas\InputFilter\Input (see https://psalm.dev/224)
        /** @psalm-trace $input */
        $input = $this->manager->get(Input::class);


ERROR: UnusedVariable - test/StaticAnalysis/InputFilterPluginManagerType.php:27:9 - $input is never referenced or the value is not used (see https://psalm.dev/077)
        /** @psalm-trace $input */
        $input = $this->manager->get(Input::class);


ERROR: Trace - test/StaticAnalysis/InputFilterPluginManagerType.php:29:9 - $input: Laminas\InputFilter\InputInterface (see https://psalm.dev/224)
        /** @psalm-trace $input */
        $input = $this->manager->get('string');

ERROR: Trace - test/StaticAnalysis/InputFilterPluginManagerType.php:31:9 - $input: Laminas\InputFilter\InputInterface (see https://psalm.dev/224)
        /** @psalm-trace $input */
        $input = $this->manager->get('stdClass');


ERROR: UnusedVariable - test/StaticAnalysis/InputFilterPluginManagerType.php:31:9 - $input is never referenced or the value is not used (see https://psalm.dev/077)
        /** @psalm-trace $input */
        $input = $this->manager->get('stdClass');


ERROR: Trace - test/StaticAnalysis/InputFilterPluginManagerType.php:33:9 - $input: LaminasTest\InputFilter\StaticAnalysis\InputFilterWithTemplatedValues (see https://psalm.dev/224)
        /** @psalm-trace $input */
        $input = $this->manager->get(InputFilterWithTemplatedValues::class);
```

For string parameters values are wrong.

However if I replace template fallback with explicit types it works out:

```
    /**
     * @inheritDoc
     * @template T of InputInterface|InputFilterInterface
     * @param class-string<T>|string $name
     * @psalm-return ($name is class-string<T> ? T : InputInterface|InputFilterInterface)
     */
    public function get($name, ?array $options = null)
```
```
ERROR: Trace - test/StaticAnalysis/InputFilterPluginManagerType.php:27:9 - $input: Laminas\InputFilter\Input (see https://psalm.dev/224)
        /** @psalm-trace $input */
        $input = $this->manager->get(Input::class);


ERROR: UnusedVariable - test/StaticAnalysis/InputFilterPluginManagerType.php:27:9 - $input is never referenced or the value is not used (see https://psalm.dev/077)
        /** @psalm-trace $input */
        $input = $this->manager->get(Input::class);


ERROR: Trace - test/StaticAnalysis/InputFilterPluginManagerType.php:29:9 - $input: Laminas\InputFilter\InputFilterInterface|Laminas\InputFilter\InputInterface (see https://psalm.dev/224)
        /** @psalm-trace $input */
        $input = $this->manager->get('string');


ERROR: UnusedVariable - test/StaticAnalysis/InputFilterPluginManagerType.php:29:9 - $input is never referenced or the value is not used (see https://psalm.dev/077)
        /** @psalm-trace $input */
        $input = $this->manager->get('string');


ERROR: Trace - test/StaticAnalysis/InputFilterPluginManagerType.php:31:9 - $input: Laminas\InputFilter\InputFilterInterface|Laminas\InputFilter\InputInterface (see https://psalm.dev/224)
        /** @psalm-trace $input */
        $input = $this->manager->get('stdClass');

ERROR: Trace - test/StaticAnalysis/InputFilterPluginManagerType.php:33:9 - $input: LaminasTest\InputFilter\StaticAnalysis\InputFilterWithTemplatedValues (see https://psalm.dev/224)
        /** @psalm-trace $input */
        $input = $this->manager->get(InputFilterWithTemplatedValues::class);
```

2024-01-09 16:22 UTC, Xerkus commented on src/InputFilterPluginManager.php
> +    }
Actually nevermind.

```
ERROR: Trace - test/StaticAnalysis/InputFilterPluginManagerType.php:32:9 - $input: PHPUnit\Framework\TestCase (see https://psalm.dev/224)
        /** @psalm-trace $input */
        $input = $this->manager->get(TestCase::class);
```
I don't think conditional actually uses template there. It creates transient template instead used only for conditional.

2024-01-09 16:43 UTC, gsteel commented on src/InputFilterPluginManager.php
> +    }
I was having problems with `class-string<InstanceType>` where `InstanceType` is the union, and similarly with `class-string<InputInterface|InputFilterInterface>` so that's why I went for `class-string<InputInterface>|class-string<InputFilterInterface>` - the simplified version is much better. I'll update the patch. Perhaps the cache was messing it up for me…

2024-01-09 16:45 UTC, Xerkus commented on src/InputFilterPluginManager.php
> +    }
The problem is psalm both accepts wrong input and allows wrong input out. look at my last comment where I used TestCase as input

2024-01-09 16:46 UTC, gsteel commented on src/Factory.php
> +        assert($inputFilter instanceof InputFilterInterface); // As opposed to InputInterface
An exception here would be a BC break though wouldn't it? The assertion will blow up in tests, it verifies the intended type for static analysis, and otherwise is a no-op for users

2024-01-09 16:48 UTC, Xerkus commented on src/Factory.php
> +        assert($inputFilter instanceof InputFilterInterface); // As opposed to InputInterface
It wouldn't be. It would just be a fatal error if method not implemented or kinda work with anything as long as object has `add()` or `__call()`

2024-01-09 16:50 UTC, Xerkus commented on src/Factory.php
> +        assert($inputFilter instanceof InputFilterInterface); // As opposed to InputInterface
This is more of a usability concern really. Exception would allow to say it needs to be input filter and get_debug_type was returned for the requested type `$type`.

2024-01-09 16:51 UTC, gsteel commented on src/InputFilterPluginManager.php
> +    }
Psalm is not wrong there because `'stdClass'` is a string, not a class-string, so it correctly yields the fallback and `InputFilterWithTemplatedValues` implements `InputFilterInterface` - it's not a TestCase, so it yields the FQCN which is exactly what we're after here. Or am I misunderstanding something?

2024-01-09 16:53 UTC, Xerkus commented on src/InputFilterPluginManager.php
> +    }
TestCase is NOT input filter and it is NOT input either. Psalm is happy about telling returned type is TestCase

2024-01-09 16:59 UTC, gsteel commented on src/InputFilterPluginManager.php
> +    }
Yeah, I just tested this. What you're saying is that Psalm will happily return `Anything` with `$manager->get(Anything::class)` - TBH, I thought that the restricted template `@template T of SpecificType` would prevent that, but it doesn't appear to.

2024-01-09 17:00 UTC, Xerkus commented on src/InputFilterPluginManager.php
> +    }
I am trying alternatives. standby

2024-01-09 17:24 UTC, Xerkus commented on src/InputFilterPluginManager.php
> +    }
Ok, so here is the results:
This is not a valid expression  `@template T of InputInterface|InputFilterInterface`. If I drop string from parameter I get:
```
ERROR: InvalidArgument - test/StaticAnalysis/InputFilterPluginManagerType.php:34:38 - Argument 1 of Laminas\InputFilter\InputFilterPluginManager::get expects class-string<Laminas\InputFilter\InputInterface>, but LaminasTest\InputFilter\StaticAnalysis\InputFilterWithTemplatedValues::class provided (see https://psalm.dev/004)
        $input = $this->manager->get(InputFilterWithTemplatedValues::class);
```
This indicates that template constraint is `InputInterface` and union part was ignored.

This is closer but has other issues:
```
    /**
     * @inheritDoc
     * @template T
     * @param class-string<T>|string $name
     * @return ($name is class-string<InputInterface>|class-string<InputFilterInterface> ? T : InputInterface|InputFilterInterface)
     */
```

Psalm then insists on throwing in mixed here
```
ERROR: MixedAssignment - src/Factory.php:174:13 - Unable to determine the type that $managerInstance is being assigned to (see https://psalm.dev/032)
            /** @psalm-trace $managerInstance */
            $managerInstance = $this->getInputFilterManager()->get($class);

  The type of $managerInstance is sourced from here - src/InputFilterPluginManager.php:194:16
     * @return ($name is class-string<InputInterface>|class-string<InputFilterInterface> ? T : InputInterface|InputFilterInterface)

ERROR: Trace - src/Factory.php:174:13 - $managerInstance: Laminas\InputFilter\InputFilterInterface|Laminas\InputFilter\InputInterface|mixed (see https://psalm.dev/224)
            /** @psalm-trace $managerInstance */
            $managerInstance = $this->getInputFilterManager()->get($class);


ERROR: MixedInferredReturnType - test/StaticAnalysis/InputFilterPluginManagerType.php:21:8 - Could not verify return type 'Laminas\InputFilter\InputFilterInterface|Laminas\InputFilter\InputInterface' for LaminasTest\InputFilter\StaticAnalysis\InputFilterPluginManagerType::getWillReturnAnInputOrInputFilterGivenAString (see https://psalm.dev/047)
    ): InputInterface|InputFilterInterface {


ERROR: MixedReturnStatement - test/StaticAnalysis/InputFilterPluginManagerType.php:22:16 - Possibly-mixed return value (see https://psalm.dev/138)
        return $this->manager->get($anyString);


ERROR: MixedReturnStatement - test/StaticAnalysis/InputFilterPluginManagerType.php:22:16 - Could not infer a return type (see https://psalm.dev/138)
        return $this->manager->get($anyString);


ERROR: Trace - test/StaticAnalysis/InputFilterPluginManagerType.php:28:9 - $input: Laminas\InputFilter\Input (see https://psalm.dev/224)
        /** @psalm-trace $input */
        $input = $this->manager->get(Input::class);


ERROR: Trace - test/StaticAnalysis/InputFilterPluginManagerType.php:30:9 - $input: Laminas\InputFilter\InputFilterInterface|Laminas\InputFilter\InputInterface (see https://psalm.dev/224)
        /** @psalm-trace $input */
        $input = $this->manager->get('string');


ERROR: Trace - test/StaticAnalysis/InputFilterPluginManagerType.php:32:9 - $input: Laminas\InputFilter\InputFilterInterface|Laminas\InputFilter\InputInterface (see https://psalm.dev/224)
        /** @psalm-trace $input */
        $input = $this->manager->get(TestCase::class);


ERROR: Trace - test/StaticAnalysis/InputFilterPluginManagerType.php:34:9 - $input: LaminasTest\InputFilter\StaticAnalysis\InputFilterWithTemplatedValues (see https://psalm.dev/224)
        /** @psalm-trace $input */
        $input = $this->manager->get(InputFilterWithTemplatedValues::class);

```

2024-01-09 17:42 UTC, Xerkus commented on src/InputFilterPluginManager.php
> +    }
This is uncharted waters and I feel we are hitting at least couple edge case bugs here.

So, for current psalm version following works:
```
    /**
     * @inheritDoc
     * // Template constraint required or we get mixed added to output. Two templates because union does not work
     * @template T1 of InputInterface
     * @template T2 of InputFilterInterface
     * // string would allow anything and both templates currently receive the passed class ignoring constraint
     * // use both templates because of the first point.
     * @param class-string<T1>|class-string<T2>|string $name
     * // We can combine conditionals and use one of templates or swap templates and it will still work. Keep both as it will likely remain working in the future
     * @return ($name is class-string<InputInterface> ? T1 : ($name is class-string<InputFilterInterface> ? T2 : InputInterface|InputFilterInterface))
     */
```

2024-01-09 17:49 UTC, Xerkus commented on src/InputFilterPluginManager.php
> +    }
@gsteel Psalm tests could be improved with https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-check-type to ensure we get expected types

I am sure it will not cause us any more grief on another lockfile maintenance PR :laughing:

2024-01-09 19:07 UTC, Xerkus requested changes
psalm conditional does not work as expected. Working variant was found. It needs to be applied and checked.

2024-01-10 10:58 UTC, gsteel commented on src/InputFilterPluginManager.php
> +    }
@xerkus - just looking at this now and unfortunately, the string case union return type is messed up:

https://psalm.dev/r/84bf036569

2024-01-10 11:23 UTC, Xerkus commented on src/InputFilterPluginManager.php
> +    }
https://psalm.dev/r/6e213fb5a6 Looks like a bug with `@psalm-check-type` not resolving FQCN against use statements and resolving against namespace for right side of union.

2024-01-10 11:29 UTC, Xerkus approved these changes

2024-01-10 11:34 UTC, Xerkus commented on psalm-baseline.xml
>      </MethodSignatureMustProvideReturnType>
Why psalm complains about plugin manager get? Does it want simple typehinted return and conditional be in psalm-return?

Also what is the MethodSignatureMismatch just above that was previously baselined? Is it due to psr container aliasing shenanigans?

2024-01-10 11:55 UTC, Xerkus commented on psalm-baseline.xml
>      </MethodSignatureMustProvideReturnType>
To answer it: some inherited weirdness going on.
```
ERROR: MethodSignatureMismatch - src/InputFilterPluginManager.php:30:7 - Method Laminas\ServiceManager\ServiceManager::has with return type '' is different to return type 'bool' of inherited method Psr\Container\ContainerInterface::has (see https://psalm.dev/042)
ERROR: MethodSignatureMismatch - src/InputFilterPluginManager.php:30:7 - Method Laminas\InputFilter\InputFilterPluginManager::get with return type '' is different to return type 'object' of inherited method Psr\Container\ContainerInterface::get (see https://psalm.dev/042)
```

2024-01-10 11:57 UTC, merged

2024-01-10 12:04 UTC, gsteel commented on psalm-baseline.xml
>      </MethodSignatureMustProvideReturnType>
I think a lot of this will be solved with SMv4 when we can drop PSR container v1 and tighten up the templates and types in the plugin manager.